"use client";

import { AlertTriangle, BarChart3, Bell, CalendarClock, Download, Eye, Filter, HeartPulse, RefreshCw, Search, Settings } from "lucide-react";
import { Badge, Button, EmptyState, ErrorState, Progress, SearchInput, Skeleton } from "@voicesense/ui";
import { aiopsStats, alerts, auditEvents, costRows, evaluations, health, liveSignals, trends } from "../../../lib/aiops-data";

export default function AnalyticsPage() {
  return (
    <div className="aiops-page">
      <header className="aiops-hero"><div><p className="ws-kicker">AI operations center</p><h1>Monitor AI employees, conversations, workflows, tools, costs, quality, health, and compliance from one command center.</h1><p>AIOps is the operational source of truth for managing AI employees at scale across every VoiceSense subsystem.</p></div><div className="aiops-actions"><Button><RefreshCw size={16} />Refresh live</Button><Button variant="outline"><Download size={16} />Export</Button><Button variant="outline"><Settings size={16} />Customize</Button></div></header>
      <section className="aiops-stat-grid">{aiopsStats.map((stat) => <article className={`aiops-card aiops-stat ${stat.tone}`} key={stat.label}><stat.icon size={18} /><p>{stat.label}</p><strong>{stat.value}</strong><span>{stat.detail}</span></article>)}</section>
      <section className="aiops-toolbar"><div className="aiops-category-row"><button className="is-active" type="button">Executive</button><button type="button">Live</button><button type="button">Quality</button><button type="button">Cost</button><button type="button">Audit</button></div><div className="aiops-search"><SearchInput placeholder="Filter by employee, team, region, status" /><Button variant="outline" size="sm"><Filter size={15} />Filters</Button></div></section>
      <section className="aiops-main-grid"><div className="aiops-left-stack"><AIOpsPanel title="Live monitoring" action={<Badge>Realtime-ready</Badge>}><div className="aiops-live-grid">{liveSignals.map((item) => <article key={item.label}><item.icon size={18} /><strong>{item.value}</strong><span>{item.label}</span><p>{item.status}</p></article>)}</div></AIOpsPanel><AIOpsPanel title="Health center" action={<Button variant="outline" size="sm"><Eye size={15} />Open health</Button>}><div className="aiops-health-grid">{health.map((item) => <div key={item.component}><item.icon size={16} /><span><strong>{item.component}</strong><small>{item.status}</small></span><Progress value={item.score} /></div>)}</div></AIOpsPanel><AIOpsPanel title="Cost intelligence"><div className="aiops-cost-table">{costRows.map((row) => <div key={row.type}><span>{row.type}</span><strong>{row.amount}</strong><small>{row.unit}</small><Badge>{row.trend}</Badge></div>)}</div></AIOpsPanel></div><aside className="aiops-side-stack"><AIOpsPanel title="Alert center"><div className="aiops-alert-list">{alerts.map((alert) => <div key={alert.title}><alert.icon size={16} /><span><strong>{alert.title}</strong><small>{alert.detail}</small></span><Badge variant={alert.severity === "warning" ? "warning" : "info"}>{alert.severity}</Badge></div>)}</div></AIOpsPanel><AIOpsPanel title="Evaluation framework"><div className="aiops-eval-grid">{evaluations.map((item) => <div key={item.label}><item.icon size={16} /><span>{item.label}</span><strong>{item.value}</strong></div>)}</div></AIOpsPanel><AIOpsPanel title="Performance trends"><div className="aiops-eval-grid">{trends.map((item) => <div key={item.label}><item.icon size={16} /><span>{item.label}</span><strong>{item.value}</strong></div>)}</div></AIOpsPanel></aside></section>
      <section className="aiops-bottom-grid"><AIOpsPanel title="Audit center"><div className="aiops-audit-list">{auditEvents.map((event) => <div className="aiops-audit" key={`${event.time}-${event.title}`}><span>{event.time}</span><event.icon size={16} /><div><strong>{event.title}</strong><p>{event.detail}</p></div></div>)}</div></AIOpsPanel><EmptyState title="Predictive optimization deferred" description="AIOps captures the data needed for recommendations, but Task 020 does not train prediction models or self-heal systems." action={<Button variant="outline" size="sm"><BarChart3 size={15} />Review metrics</Button>} /><div className="aiops-card"><Skeleton className="aiops-skeleton" /><Skeleton className="aiops-skeleton-line" /><Skeleton className="aiops-skeleton-line" /></div></section>
      <section className="aiops-state-grid"><ErrorState title="Provider outage simulation" description="Provider outage alerts are modeled and ready for future notification delivery channels." onRetry={() => undefined} /><EmptyState title="No saved personal dashboard" description="Users can model personal and organization dashboards with custom layouts and widgets." action={<Button variant="outline" size="sm"><CalendarClock size={15} />Create layout</Button>} /></section>
    </div>
  );
}
function AIOpsPanel({ title, action, children }: { title: string; action?: React.ReactNode; children: React.ReactNode }) { return <article className="aiops-card"><div className="aiops-panel-head"><h2>{title}</h2>{action}</div>{children}</article>; }
