"use client";

import { Bot, BrainCircuit, GitBranch, KeyRound, Network, Plus, RefreshCw, Search, Settings, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { Badge, Button, EmptyState, ErrorState, Progress, SearchInput, Skeleton } from "@voicesense/ui";
import { analytics, delegations, orgNodes, policies, teamStats, teams, timeline } from "../../../lib/team-data";

export default function TeamsPage() {
  return (
    <div className="team-page">
      <header className="team-hero"><div><p className="ws-kicker">Multi-agent collaboration</p><h1>Design AI departments where supervisors, specialists, and assistants coordinate work together.</h1><p>Manage AI teams, delegation policies, shared context, supervisor review, routing, and traceable collaboration timelines across the platform.</p></div><div className="team-actions"><Button><Plus size={16} />Create team</Button><Button variant="outline"><GitBranch size={16} />Delegate task</Button><Button variant="outline"><Settings size={16} />Policies</Button></div></header>
      <section className="team-stat-grid">{teamStats.map((stat) => <article className={`team-card team-stat ${stat.tone}`} key={stat.label}><stat.icon size={18} /><p>{stat.label}</p><strong>{stat.value}</strong><span>{stat.detail}</span></article>)}</section>
      <section className="team-toolbar"><div className="team-category-row"><button className="is-active" type="button">Teams</button><button type="button">Departments</button><button type="button">Supervisors</button><button type="button">Policies</button></div><div className="team-search"><SearchInput placeholder="Search teams, roles, objectives" /><Button variant="outline" size="sm"><Search size={15} />Search</Button></div></section>
      <section className="team-main-grid"><div className="team-left-stack"><TeamPanel title="AI team dashboard" action={<Button variant="outline" size="sm"><RefreshCw size={15} />Refresh</Button>}><div className="team-table"><div className="team-row team-head"><span>Team</span><span>Department</span><span>Supervisor</span><span>Status</span><span>Members</span><span>Load</span></div>{teams.map((team) => <div className="team-row" key={team.name}><span><UsersRound size={16} />{team.name}</span><span>{team.department}</span><span>{team.supervisor}</span><span><Badge variant={team.status === "Active" ? "success" : "warning"}>{team.status}</Badge></span><span>{team.members}</span><span><Progress value={team.load} /></span></div>)}</div></TeamPanel><TeamPanel title="Organization chart"><div className="team-org-chart">{orgNodes.map((node, index) => <article key={node.label}><span>{index + 1}</span><node.icon size={18} /><strong>{node.label}</strong><p>{node.role}</p></article>)}</div></TeamPanel><TeamPanel title="Delegation viewer"><div className="team-delegation-list">{delegations.map((item) => <div key={item.task}><GitBranch size={16} /><span><strong>{item.task}</strong><small>{item.route}</small></span><Badge>{item.confidence}</Badge><em>{item.status}</em></div>)}</div></TeamPanel></div><aside className="team-side-stack"><TeamPanel title="Supervisor dashboard"><div className="team-supervisor"><ShieldCheck size={22} /><strong>Supervisor AI monitors assignments, validates decisions, resolves conflicts, and escalates issues.</strong><p>Supervisor behavior is modeled through team records, policy rules, and collaboration sessions. Autonomous supervisor reasoning comes later.</p></div></TeamPanel><TeamPanel title="Policy management"><div className="team-policy-grid">{policies.map((policy) => <div key={policy.name}><policy.icon size={16} /><span>{policy.name}</span><strong>{policy.value}</strong></div>)}</div></TeamPanel><TeamPanel title="Team analytics"><div className="team-analytics-grid">{analytics.map((item) => <div key={item.label}><item.icon size={16} /><span>{item.label}</span><strong>{item.value}</strong></div>)}</div></TeamPanel></aside></section>
      <section className="team-bottom-grid"><TeamPanel title="Collaboration timeline"><div className="team-timeline">{timeline.map((event) => <div className="team-event" key={`${event.time}-${event.title}`}><span>{event.time}</span><event.icon size={16} /><div><strong>{event.title}</strong><p>{event.detail}</p></div></div>)}</div></TeamPanel><EmptyState title="Shared memory is permission-aware" description="Shared facts, notes, decisions, and task history reference the Memory System while preserving organization and team boundaries." action={<Button variant="outline" size="sm"><BrainCircuit size={15} />Review memory</Button>} /><div className="team-card"><Skeleton className="team-skeleton" /><Skeleton className="team-skeleton-line" /><Skeleton className="team-skeleton-line" /></div></section>
      <section className="team-state-grid"><ErrorState title="Autonomous learning disabled" description="Task 019 builds collaboration infrastructure only. AI employees do not self-modify behavior or learn autonomously." onRetry={() => undefined} /><EmptyState title="No conflict selected" description="Duplicate assignments, conflicting decisions, timeouts, retries, and escalations are modeled for future runtime resolution." action={<Button variant="outline" size="sm"><Sparkles size={15} />Open conflicts</Button>} /></section>
    </div>
  );
}
function TeamPanel({ title, action, children }: { title: string; action?: React.ReactNode; children: React.ReactNode }) { return <article className="team-card"><div className="team-panel-head"><h2>{title}</h2>{action}</div>{children}</article>; }
