"use client";

import type { ReactNode } from "react";
import { Phone, Plus, RefreshCw, Route, Search, Settings, ShieldCheck } from "lucide-react";
import { Badge, Button, EmptyState, ErrorState, Progress, SearchInput, Skeleton } from "@voicesense/ui";
import { callAnalytics, callTimeline, numbers, providers, queues, sipReadiness, telephonyAlerts, telephonyStats } from "../../../lib/telephony-data";

export default function TelephonyPage() {
  return (
    <div className="telephony-page">
      <header className="telephony-hero"><div><p className="ws-kicker">Enterprise telephony</p><h1>Operate provider-independent voice communications, numbers, queues, routing, SIP, recordings, and live call monitoring.</h1><p>Telephony powers the call backbone from provider gateway to Voice Engine, Conversation Engine, workflows, AI employees, and tool runtime.</p></div><div className="telephony-actions"><Button><Phone size={16} />Create call</Button><Button variant="outline"><Plus size={16} />Import number</Button><Button variant="outline"><Settings size={16} />Providers</Button></div></header>
      <section className="telephony-stat-grid">{telephonyStats.map((stat) => <article className={`telephony-card telephony-stat ${stat.tone}`} key={stat.label}><stat.icon size={18} /><p>{stat.label}</p><strong>{stat.value}</strong><span>{stat.detail}</span></article>)}</section>
      <section className="telephony-toolbar"><div className="telephony-category-row"><button className="is-active" type="button">Live calls</button><button type="button">Numbers</button><button type="button">Queues</button><button type="button">Routing</button><button type="button">SIP</button></div><div className="telephony-search"><SearchInput placeholder="Search calls, numbers, customers, outcomes" /><Button variant="outline" size="sm"><Search size={15} />Search</Button></div></section>
      <section className="telephony-main-grid"><div className="telephony-left-stack"><TelephonyPanel title="Provider health" action={<Button variant="outline" size="sm"><RefreshCw size={15} />Refresh</Button>}><div className="telephony-provider-grid">{providers.map((provider) => <article key={provider.name}><strong>{provider.name}</strong><p>{provider.provider} - {provider.region}</p><Badge variant={provider.status === "Enabled" ? "success" : "warning"}>{provider.status}</Badge><span>{provider.latency}</span><Progress value={provider.health} /></article>)}</div></TelephonyPanel><TelephonyPanel title="Number management"><div className="telephony-table"><div className="telephony-row telephony-head"><span>Number</span><span>Label</span><span>Route</span><span>Status</span><span>Region</span></div>{numbers.map((number) => <div className="telephony-row" key={number.number}><span><Phone size={16} />{number.number}</span><span>{number.label}</span><span>{number.route}</span><span><Badge variant={number.status === "Active" ? "success" : "info"}>{number.status}</Badge></span><span>{number.region}</span></div>)}</div></TelephonyPanel><TelephonyPanel title="Real-time call timeline"><div className="telephony-timeline">{callTimeline.map((event) => <div className="telephony-event" key={`${event.time}-${event.title}`}><span>{event.time}</span><event.icon size={16} /><div><strong>{event.title}</strong><p>{event.detail}</p></div></div>)}</div></TelephonyPanel></div><aside className="telephony-side-stack"><TelephonyPanel title="Call queues"><div className="telephony-queue-list">{queues.map((queue) => <div key={queue.name}><span><strong>{queue.name}</strong><small>{queue.priority} - {queue.overflow}</small></span><Badge>{queue.waiting} waiting</Badge><p>{queue.wait}</p></div>)}</div></TelephonyPanel><TelephonyPanel title="SIP and recording readiness"><div className="telephony-readiness-grid">{sipReadiness.map((item) => <div key={item.label}><item.icon size={16} /><span>{item.label}</span><strong>{item.value}</strong></div>)}</div></TelephonyPanel><TelephonyPanel title="Call analytics"><div className="telephony-readiness-grid">{callAnalytics.map((item) => <div key={item.label}><item.icon size={16} /><span>{item.label}</span><strong>{item.value}</strong></div>)}</div></TelephonyPanel></aside></section>
      <section className="telephony-bottom-grid"><TelephonyPanel title="Operational alerts"><div className="telephony-alert-list">{telephonyAlerts.map((alert) => <div key={alert.title}><alert.icon size={16} /><span><strong>{alert.title}</strong><small>{alert.detail}</small></span><Badge variant="warning">watch</Badge></div>)}</div></TelephonyPanel><EmptyState title="Provider provisioning deferred" description="Provider accounts, phone number purchases, and payments are intentionally outside Task 021. The abstraction and management foundation are ready." action={<Button variant="outline" size="sm"><Route size={15} />Review routing</Button>} /><div className="telephony-card"><Skeleton className="telephony-skeleton" /><Skeleton className="telephony-skeleton-line" /><Skeleton className="telephony-skeleton-line" /></div></section>
      <section className="telephony-state-grid"><ErrorState title="Human agent desktop not included" description="Queues and transfers are modeled for future contact center features, but workforce management is out of scope." onRetry={() => undefined} /><EmptyState title="Recording access is policy controlled" description="Recording metadata, retention, secure storage refs, pause, and resume architecture are modeled for future runtime recording." action={<Button variant="outline" size="sm"><ShieldCheck size={15} />Review policy</Button>} /></section>
    </div>
  );
}
function TelephonyPanel({ title, action, children }: { title: string; action?: ReactNode; children: ReactNode }) { return <article className="telephony-card"><div className="telephony-panel-head"><h2>{title}</h2>{action}</div>{children}</article>; }
