"use client";

import type { ReactNode } from "react";
import { MessageCircle, Plus, RefreshCw, Search, Settings, ShieldCheck } from "lucide-react";
import { Badge, Button, EmptyState, ErrorState, Progress, SearchInput, Skeleton } from "@voicesense/ui";
import { channelCards, customerTimeline, deliveryMetrics, omniStats, readiness, sessions } from "../../../lib/omnichannel-data";

export default function OmnichannelPage() {
  return (
    <div className="omni-page">
      <header className="omni-hero"><div><p className="ws-kicker">Omnichannel communications</p><h1>Unify every customer conversation across voice, WhatsApp, email, SMS, web chat, Slack, Teams, mobile, and future channels.</h1><p>AI employees keep one customer identity, one conversation history, one workflow state, and one timeline while channel adapters handle provider-specific details.</p></div><div className="omni-actions"><Button><MessageCircle size={16} />Send message</Button><Button variant="outline"><Plus size={16} />Add channel</Button><Button variant="outline"><Settings size={16} />Configure</Button></div></header>
      <section className="omni-stat-grid">{omniStats.map((stat) => <article className={`omni-card omni-stat ${stat.tone}`} key={stat.label}><stat.icon size={18} /><p>{stat.label}</p><strong>{stat.value}</strong><span>{stat.detail}</span></article>)}</section>
      <section className="omni-toolbar"><div className="omni-category-row"><button className="is-active" type="button">Unified inbox</button><button type="button">Channels</button><button type="button">Timeline</button><button type="button">Delivery</button><button type="button">Identity</button></div><div className="omni-search"><SearchInput placeholder="Search customers, channels, sessions, messages" /><Button variant="outline" size="sm"><Search size={15} />Search</Button></div></section>
      <section className="omni-main-grid"><div className="omni-left-stack"><OmniPanel title="Channel health" action={<Button variant="outline" size="sm"><RefreshCw size={15} />Refresh</Button>}><div className="omni-channel-grid">{channelCards.map((channel) => <article key={channel.name}><channel.icon size={18} /><strong>{channel.name}</strong><p>{channel.provider}</p><Badge variant={channel.status === "Operational" ? "success" : "warning"}>{channel.status}</Badge><span>{channel.latency}</span><Progress value={channel.status === "Operational" ? 96 : 72} /></article>)}</div></OmniPanel><OmniPanel title="Unified customer timeline"><div className="omni-timeline">{customerTimeline.map((event) => <div className="omni-event" key={`${event.time}-${event.title}`}><span>{event.time}</span><event.icon size={16} /><div><Badge variant="info">{event.channel}</Badge><strong>{event.title}</strong><p>{event.detail}</p></div></div>)}</div></OmniPanel><OmniPanel title="Active channel sessions"><div className="omni-table"><div className="omni-row omni-head"><span>Customer</span><span>Channel</span><span>Identity</span><span>Status</span><span>Continuation</span></div>{sessions.map((session) => <div className="omni-row" key={session.customer}><span>{session.customer}</span><span>{session.channel}</span><span>{session.identity}</span><span><Badge variant={session.status === "Active" ? "success" : "warning"}>{session.status}</Badge></span><span>{session.continuation}</span></div>)}</div></OmniPanel></div><aside className="omni-side-stack"><OmniPanel title="Delivery tracking"><div className="omni-readiness-grid">{deliveryMetrics.map((item) => <div key={item.label}><item.icon size={16} /><span>{item.label}</span><strong>{item.value}</strong></div>)}</div></OmniPanel><OmniPanel title="Platform readiness"><div className="omni-readiness-grid">{readiness.map((item) => <div key={item.label}><item.icon size={16} /><span>{item.label}</span><strong>{item.value}</strong></div>)}</div></OmniPanel><EmptyState title="Provider credentials deferred" description="Production provider credentials, billing, and campaign automation are intentionally outside Task 022." action={<Button variant="outline" size="sm"><ShieldCheck size={15} />Review security</Button>} /></aside></section>
      <section className="omni-bottom-grid"><EmptyState title="Smart channel selection ready" description="The data model can support AI channel choice by preference, urgency, cost, availability, and business rules." action={<Button variant="outline" size="sm">Open policy</Button>} /><ErrorState title="Human live chat not included" description="The platform models sessions and timelines for future handoff, but a live human agent console is out of scope." onRetry={() => undefined} /><div className="omni-card"><Skeleton className="omni-skeleton" /><Skeleton className="omni-skeleton-line" /><Skeleton className="omni-skeleton-line" /></div></section>
    </div>
  );
}

function OmniPanel({ title, action, children }: { title: string; action?: ReactNode; children: ReactNode }) { return <article className="omni-card"><div className="omni-panel-head"><h2>{title}</h2>{action}</div>{children}</article>; }
