CREATE TABLE IF NOT EXISTS ai_roles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, name VARCHAR(160) NOT NULL, slug VARCHAR(120) NOT NULL, category VARCHAR(80) NOT NULL DEFAULT 'custom', description TEXT, responsibilities JSONB NOT NULL DEFAULT '[]'::jsonb, permissions JSONB NOT NULL DEFAULT '{}'::jsonb, metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, status VARCHAR(40) NOT NULL DEFAULT 'active', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ, CONSTRAINT uq_ai_role_workspace_slug UNIQUE (workspace_id, slug)
);
CREATE TABLE IF NOT EXISTS ai_teams (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, parent_team_id UUID REFERENCES ai_teams(id) ON DELETE SET NULL, supervisor_agent_id UUID REFERENCES agents(id) ON DELETE SET NULL, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, name VARCHAR(180) NOT NULL, slug VARCHAR(140) NOT NULL, department VARCHAR(120), description TEXT, responsibilities JSONB NOT NULL DEFAULT '[]'::jsonb, routing_policy JSONB NOT NULL DEFAULT '{}'::jsonb, collaboration_rules JSONB NOT NULL DEFAULT '{}'::jsonb, status VARCHAR(40) NOT NULL DEFAULT 'active', metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ, CONSTRAINT uq_ai_team_workspace_slug UNIQUE (workspace_id, slug)
);
CREATE TABLE IF NOT EXISTS ai_team_members (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, team_id UUID NOT NULL REFERENCES ai_teams(id) ON DELETE CASCADE, agent_id UUID NOT NULL REFERENCES agents(id) ON DELETE CASCADE, role_id UUID REFERENCES ai_roles(id) ON DELETE SET NULL, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, membership_type VARCHAR(60) NOT NULL DEFAULT 'member', responsibilities JSONB NOT NULL DEFAULT '[]'::jsonb, availability_state JSONB NOT NULL DEFAULT '{}'::jsonb, workload_score INTEGER NOT NULL DEFAULT 0, status VARCHAR(40) NOT NULL DEFAULT 'active', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ, CONSTRAINT uq_ai_team_member_agent UNIQUE (team_id, agent_id)
);
CREATE TABLE IF NOT EXISTS collaboration_policies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, team_id UUID REFERENCES ai_teams(id) ON DELETE CASCADE, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, name VARCHAR(180) NOT NULL, policy_type VARCHAR(80) NOT NULL, max_delegation_depth INTEGER NOT NULL DEFAULT 4, allowed_delegations JSONB NOT NULL DEFAULT '{}'::jsonb, approval_requirements JSONB NOT NULL DEFAULT '{}'::jsonb, escalation_rules JSONB NOT NULL DEFAULT '{}'::jsonb, department_restrictions JSONB NOT NULL DEFAULT '{}'::jsonb, status VARCHAR(40) NOT NULL DEFAULT 'active', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS collaboration_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, team_id UUID REFERENCES ai_teams(id) ON DELETE SET NULL, conversation_id UUID REFERENCES conversations(id) ON DELETE SET NULL, workflow_run_id UUID REFERENCES workflow_runs(id) ON DELETE SET NULL, supervisor_agent_id UUID REFERENCES agents(id) ON DELETE SET NULL, objective TEXT NOT NULL, status VARCHAR(40) NOT NULL DEFAULT 'active', priority VARCHAR(40) NOT NULL DEFAULT 'normal', shared_state JSONB NOT NULL DEFAULT '{}'::jsonb, success_criteria JSONB NOT NULL DEFAULT '{}'::jsonb, started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS delegation_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, session_id UUID REFERENCES collaboration_sessions(id) ON DELETE CASCADE, source_agent_id UUID REFERENCES agents(id) ON DELETE SET NULL, target_agent_id UUID REFERENCES agents(id) ON DELETE SET NULL, team_id UUID REFERENCES ai_teams(id) ON DELETE SET NULL, task_title VARCHAR(200) NOT NULL, task_payload JSONB NOT NULL DEFAULT '{}'::jsonb, routing_reason TEXT, confidence_score NUMERIC(5,2), depth INTEGER NOT NULL DEFAULT 0, status VARCHAR(40) NOT NULL DEFAULT 'assigned', due_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS shared_contexts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, session_id UUID NOT NULL REFERENCES collaboration_sessions(id) ON DELETE CASCADE, context_type VARCHAR(80) NOT NULL, key VARCHAR(160) NOT NULL, value_json JSONB NOT NULL DEFAULT '{}'::jsonb, visibility VARCHAR(60) NOT NULL DEFAULT 'team', source_agent_id UUID REFERENCES agents(id) ON DELETE SET NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS shared_memory_refs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, session_id UUID NOT NULL REFERENCES collaboration_sessions(id) ON DELETE CASCADE, memory_id UUID REFERENCES memories(id) ON DELETE SET NULL, reference_type VARCHAR(80) NOT NULL DEFAULT 'fact', summary TEXT, permission_summary JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS collaboration_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, session_id UUID REFERENCES collaboration_sessions(id) ON DELETE CASCADE, sender_agent_id UUID REFERENCES agents(id) ON DELETE SET NULL, recipient_agent_id UUID REFERENCES agents(id) ON DELETE SET NULL, message_type VARCHAR(80) NOT NULL DEFAULT 'direct', subject VARCHAR(180), body TEXT, payload JSONB NOT NULL DEFAULT '{}'::jsonb, status VARCHAR(40) NOT NULL DEFAULT 'sent', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS collaboration_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, session_id UUID REFERENCES collaboration_sessions(id) ON DELETE CASCADE, event_type VARCHAR(100) NOT NULL, actor_agent_id UUID REFERENCES agents(id) ON DELETE SET NULL, level VARCHAR(40) NOT NULL DEFAULT 'info', message TEXT, payload JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS collaboration_metrics (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, team_id UUID REFERENCES ai_teams(id) ON DELETE CASCADE, metric_name VARCHAR(80) NOT NULL, metric_value NUMERIC(14,3) NOT NULL, unit VARCHAR(32) NOT NULL DEFAULT 'count', dimensions JSONB NOT NULL DEFAULT '{}'::jsonb, captured_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_ai_teams_workspace_status ON ai_teams(workspace_id, status, department);
CREATE INDEX IF NOT EXISTS ix_ai_team_members_team_status ON ai_team_members(team_id, status, membership_type);
CREATE INDEX IF NOT EXISTS ix_collab_sessions_workspace_status ON collaboration_sessions(workspace_id, status, started_at);
CREATE INDEX IF NOT EXISTS ix_delegation_events_session_status ON delegation_events(session_id, status, created_at);
CREATE INDEX IF NOT EXISTS ix_shared_context_session_key ON shared_contexts(session_id, context_type, key);
CREATE INDEX IF NOT EXISTS ix_collab_messages_session_type ON collaboration_messages(session_id, message_type, created_at);
CREATE INDEX IF NOT EXISTS ix_collab_logs_session_event ON collaboration_logs(session_id, event_type, created_at);
CREATE INDEX IF NOT EXISTS ix_collab_metrics_team_time ON collaboration_metrics(team_id, metric_name, captured_at);