CREATE TABLE IF NOT EXISTS ops_dashboards (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, owner_user_id UUID REFERENCES users(id) ON DELETE SET NULL, name VARCHAR(180) NOT NULL, scope VARCHAR(60) NOT NULL DEFAULT 'workspace', layout JSONB NOT NULL DEFAULT '{}'::jsonb, filters JSONB NOT NULL DEFAULT '{}'::jsonb, widgets JSONB NOT NULL DEFAULT '[]'::jsonb, is_default BOOLEAN NOT NULL DEFAULT false, status VARCHAR(40) NOT NULL DEFAULT 'active', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS ops_metrics (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, metric_name VARCHAR(120) NOT NULL, metric_family VARCHAR(80) NOT NULL, entity_type VARCHAR(80), entity_id UUID, value NUMERIC(18,6) NOT NULL, unit VARCHAR(40) NOT NULL DEFAULT 'count', dimensions JSONB NOT NULL DEFAULT '{}'::jsonb, captured_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS ops_alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, name VARCHAR(180) NOT NULL, alert_type VARCHAR(80) NOT NULL, severity VARCHAR(40) NOT NULL DEFAULT 'warning', status VARCHAR(40) NOT NULL DEFAULT 'active', condition JSONB NOT NULL DEFAULT '{}'::jsonb, channels JSONB NOT NULL DEFAULT '[]'::jsonb, last_triggered_at TIMESTAMPTZ, metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS ops_alert_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, alert_id UUID REFERENCES ops_alerts(id) ON DELETE SET NULL, severity VARCHAR(40) NOT NULL, status VARCHAR(40) NOT NULL DEFAULT 'open', title VARCHAR(200) NOT NULL, description TEXT, source VARCHAR(80) NOT NULL, entity_type VARCHAR(80), entity_id UUID, payload JSONB NOT NULL DEFAULT '{}'::jsonb, resolved_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS ops_health_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, component VARCHAR(100) NOT NULL, status VARCHAR(40) NOT NULL, score INTEGER NOT NULL DEFAULT 100, checks JSONB NOT NULL DEFAULT '{}'::jsonb, incidents JSONB NOT NULL DEFAULT '[]'::jsonb, measured_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS ops_cost_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, cost_type VARCHAR(80) NOT NULL, provider VARCHAR(80), entity_type VARCHAR(80), entity_id UUID, amount NUMERIC(18,6) NOT NULL, currency VARCHAR(12) NOT NULL DEFAULT 'USD', quantity NUMERIC(18,6), unit VARCHAR(40), occurred_at TIMESTAMPTZ NOT NULL, metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS ops_evaluation_results (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, agent_id UUID REFERENCES agents(id) ON DELETE SET NULL, conversation_id UUID REFERENCES conversations(id) ON DELETE SET NULL, reviewed_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, evaluation_type VARCHAR(80) NOT NULL, score NUMERIC(8,3), status VARCHAR(40) NOT NULL DEFAULT 'pending', evaluator VARCHAR(80) NOT NULL DEFAULT 'framework', criteria JSONB NOT NULL DEFAULT '{}'::jsonb, result JSONB NOT NULL DEFAULT '{}'::jsonb, evaluated_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_ops_metrics_workspace_family_time ON ops_metrics(workspace_id, metric_family, captured_at);
CREATE INDEX IF NOT EXISTS ix_ops_alerts_workspace_status ON ops_alerts(workspace_id, status, severity);
CREATE INDEX IF NOT EXISTS ix_ops_alert_events_workspace_status ON ops_alert_events(workspace_id, status, severity);
CREATE INDEX IF NOT EXISTS ix_ops_health_component_time ON ops_health_reports(workspace_id, component, measured_at);
CREATE INDEX IF NOT EXISTS ix_ops_cost_records_type_time ON ops_cost_records(workspace_id, cost_type, occurred_at);
CREATE INDEX IF NOT EXISTS ix_ops_evaluations_agent_type ON ops_evaluation_results(workspace_id, agent_id, evaluation_type);