CREATE TABLE IF NOT EXISTS telephony_provider_configs (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, name VARCHAR(160) NOT NULL, provider VARCHAR(80) NOT NULL, status VARCHAR(40) NOT NULL DEFAULT 'disabled', priority INTEGER NOT NULL DEFAULT 100, region VARCHAR(80), secret_ref TEXT, capabilities JSONB NOT NULL DEFAULT '[]'::jsonb, failover_policy JSONB NOT NULL DEFAULT '{}'::jsonb, health_state JSONB NOT NULL DEFAULT '{}'::jsonb, config JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ, CONSTRAINT uq_telephony_provider_name UNIQUE (workspace_id, provider, name)
);
CREATE TABLE IF NOT EXISTS call_queues (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, name VARCHAR(160) NOT NULL, slug VARCHAR(120) NOT NULL, priority INTEGER NOT NULL DEFAULT 100, overflow_policy JSONB NOT NULL DEFAULT '{}'::jsonb, assignment_policy JSONB NOT NULL DEFAULT '{}'::jsonb, estimated_wait_seconds INTEGER, status VARCHAR(40) NOT NULL DEFAULT 'active', analytics_state JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS phone_numbers (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, provider_config_id UUID REFERENCES telephony_provider_configs(id) ON DELETE SET NULL, assigned_agent_id UUID REFERENCES agents(id) ON DELETE SET NULL, queue_id UUID REFERENCES call_queues(id) ON DELETE SET NULL, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, e164 VARCHAR(32) NOT NULL, label VARCHAR(160), number_type VARCHAR(40) NOT NULL DEFAULT 'local', country VARCHAR(8), region VARCHAR(80), status VARCHAR(40) NOT NULL DEFAULT 'active', routing_config JSONB NOT NULL DEFAULT '{}'::jsonb, compliance_config JSONB NOT NULL DEFAULT '{}'::jsonb, metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ, CONSTRAINT uq_phone_number_workspace_e164 UNIQUE (workspace_id, e164)
);
CREATE TABLE IF NOT EXISTS sip_endpoints (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, provider_config_id UUID REFERENCES telephony_provider_configs(id) ON DELETE SET NULL, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, name VARCHAR(160) NOT NULL, domain VARCHAR(180) NOT NULL, endpoint_type VARCHAR(60) NOT NULL DEFAULT 'trunk', auth_type VARCHAR(60) NOT NULL DEFAULT 'digest', secret_ref TEXT, allowed_ips JSONB NOT NULL DEFAULT '[]'::jsonb, headers JSONB NOT NULL DEFAULT '{}'::jsonb, routing_config JSONB NOT NULL DEFAULT '{}'::jsonb, status VARCHAR(40) NOT NULL DEFAULT 'disabled', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS call_routing_rules (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, phone_number_id UUID REFERENCES phone_numbers(id) ON DELETE CASCADE, queue_id UUID REFERENCES call_queues(id) ON DELETE SET NULL, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, name VARCHAR(160) NOT NULL, priority INTEGER NOT NULL DEFAULT 100, status VARCHAR(40) NOT NULL DEFAULT 'active', conditions JSONB NOT NULL DEFAULT '{}'::jsonb, destination_type VARCHAR(60) NOT NULL DEFAULT 'agent', destination_ref VARCHAR(180), business_hours JSONB NOT NULL DEFAULT '{}'::jsonb, failover JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS telephony_calls (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, provider_config_id UUID REFERENCES telephony_provider_configs(id) ON DELETE SET NULL, phone_number_id UUID REFERENCES phone_numbers(id) ON DELETE SET NULL, queue_id UUID REFERENCES call_queues(id) ON DELETE SET NULL, voice_session_id UUID REFERENCES voice_sessions(id) ON DELETE SET NULL, conversation_id UUID REFERENCES conversations(id) ON DELETE SET NULL, workflow_run_id UUID REFERENCES workflow_runs(id) ON DELETE SET NULL, agent_id UUID REFERENCES agents(id) ON DELETE SET NULL, provider_call_id VARCHAR(180), direction VARCHAR(40) NOT NULL DEFAULT 'inbound', call_type VARCHAR(40) NOT NULL DEFAULT 'pstn', status VARCHAR(40) NOT NULL DEFAULT 'created', from_number VARCHAR(40), to_number VARCHAR(40), customer_ref VARCHAR(180), routing_result JSONB NOT NULL DEFAULT '{}'::jsonb, timeline_state JSONB NOT NULL DEFAULT '{}'::jsonb, cost_state JSONB NOT NULL DEFAULT '{}'::jsonb, started_at TIMESTAMPTZ, answered_at TIMESTAMPTZ, ended_at TIMESTAMPTZ, duration_seconds INTEGER, end_reason TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS telephony_call_events (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, call_id UUID NOT NULL REFERENCES telephony_calls(id) ON DELETE CASCADE, event_type VARCHAR(100) NOT NULL, sequence_number INTEGER NOT NULL DEFAULT 0, source VARCHAR(80) NOT NULL DEFAULT 'telephony', payload JSONB NOT NULL DEFAULT '{}'::jsonb, latency_ms INTEGER, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS call_recordings (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, call_id UUID NOT NULL REFERENCES telephony_calls(id) ON DELETE CASCADE, storage_object_id UUID REFERENCES files(id) ON DELETE SET NULL, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, status VARCHAR(40) NOT NULL DEFAULT 'metadata_only', recording_type VARCHAR(40) NOT NULL DEFAULT 'full', retention_policy JSONB NOT NULL DEFAULT '{}'::jsonb, access_policy JSONB NOT NULL DEFAULT '{}'::jsonb, started_at TIMESTAMPTZ, stopped_at TIMESTAMPTZ, duration_seconds INTEGER, metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS call_metrics (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, call_id UUID REFERENCES telephony_calls(id) ON DELETE CASCADE, metric_name VARCHAR(80) NOT NULL, metric_value NUMERIC(14,3) NOT NULL, unit VARCHAR(32) NOT NULL DEFAULT 'count', dimensions JSONB NOT NULL DEFAULT '{}'::jsonb, captured_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_telephony_providers_workspace_status ON telephony_provider_configs(workspace_id, status, priority);
CREATE INDEX IF NOT EXISTS ix_phone_numbers_workspace_status ON phone_numbers(workspace_id, status, country);
CREATE INDEX IF NOT EXISTS ix_telephony_calls_workspace_status ON telephony_calls(workspace_id, status, started_at);
CREATE INDEX IF NOT EXISTS ix_telephony_calls_numbers ON telephony_calls(from_number, to_number, started_at);
CREATE INDEX IF NOT EXISTS ix_telephony_call_events_call_sequence ON telephony_call_events(call_id, sequence_number);
CREATE INDEX IF NOT EXISTS ix_call_metrics_workspace_name ON call_metrics(workspace_id, metric_name, captured_at);