CREATE TABLE IF NOT EXISTS channel_configurations (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, name VARCHAR(160) NOT NULL, channel_type VARCHAR(60) NOT NULL, provider VARCHAR(80) NOT NULL, status VARCHAR(40) NOT NULL DEFAULT 'disabled', priority INTEGER NOT NULL DEFAULT 100, region VARCHAR(80), secret_ref TEXT, capabilities JSONB NOT NULL DEFAULT '{}'::jsonb, formatter_policy JSONB NOT NULL DEFAULT '{}'::jsonb, health_state JSONB NOT NULL DEFAULT '{}'::jsonb, config JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ, CONSTRAINT uq_channel_config_workspace_type_name UNIQUE (workspace_id, channel_type, name)
);
CREATE TABLE IF NOT EXISTS customer_identities (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, display_name VARCHAR(180), identity_type VARCHAR(60) NOT NULL, identity_value VARCHAR(320) NOT NULL, canonical_customer_ref VARCHAR(180), confidence_score NUMERIC(5,3), source VARCHAR(80) NOT NULL DEFAULT 'omnichannel', merge_state JSONB NOT NULL DEFAULT '{}'::jsonb, profile JSONB NOT NULL DEFAULT '{}'::jsonb, preferences JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ, CONSTRAINT uq_customer_identity_workspace_value UNIQUE (workspace_id, identity_type, identity_value)
);
CREATE TABLE IF NOT EXISTS channel_sessions (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, channel_config_id UUID REFERENCES channel_configurations(id) ON DELETE SET NULL, customer_identity_id UUID REFERENCES customer_identities(id) ON DELETE SET NULL, conversation_id UUID REFERENCES conversations(id) ON DELETE SET NULL, agent_id UUID REFERENCES agents(id) ON DELETE SET NULL, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, external_thread_id VARCHAR(220), channel_type VARCHAR(60) NOT NULL, status VARCHAR(40) NOT NULL DEFAULT 'active', subject VARCHAR(260), context_state JSONB NOT NULL DEFAULT '{}'::jsonb, workflow_state JSONB NOT NULL DEFAULT '{}'::jsonb, last_message_at TIMESTAMPTZ, expires_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS omnichannel_messages (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, channel_session_id UUID REFERENCES channel_sessions(id) ON DELETE SET NULL, channel_config_id UUID REFERENCES channel_configurations(id) ON DELETE SET NULL, customer_identity_id UUID REFERENCES customer_identities(id) ON DELETE SET NULL, conversation_id UUID REFERENCES conversations(id) ON DELETE SET NULL, agent_id UUID REFERENCES agents(id) ON DELETE SET NULL, direction VARCHAR(40) NOT NULL DEFAULT 'inbound', channel_type VARCHAR(60) NOT NULL, message_type VARCHAR(60) NOT NULL DEFAULT 'text', provider_message_id VARCHAR(220), sender_ref VARCHAR(220), recipient_ref VARCHAR(220), subject VARCHAR(260), text_body TEXT, normalized_payload JSONB NOT NULL DEFAULT '{}'::jsonb, formatted_payload JSONB NOT NULL DEFAULT '{}'::jsonb, status VARCHAR(40) NOT NULL DEFAULT 'received', sent_at TIMESTAMPTZ, delivered_at TIMESTAMPTZ, read_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS message_attachments (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, message_id UUID REFERENCES omnichannel_messages(id) ON DELETE CASCADE, storage_object_id UUID REFERENCES files(id) ON DELETE SET NULL, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, attachment_type VARCHAR(60) NOT NULL, filename VARCHAR(260), content_type VARCHAR(120), size_bytes INTEGER, scan_state JSONB NOT NULL DEFAULT '{}'::jsonb, access_policy JSONB NOT NULL DEFAULT '{}'::jsonb, metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS delivery_events (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, message_id UUID NOT NULL REFERENCES omnichannel_messages(id) ON DELETE CASCADE, event_type VARCHAR(80) NOT NULL, provider VARCHAR(80), provider_event_id VARCHAR(220), status VARCHAR(40) NOT NULL, attempt INTEGER NOT NULL DEFAULT 1, latency_ms INTEGER, error_code VARCHAR(120), payload JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS customer_timeline_events (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, customer_identity_id UUID REFERENCES customer_identities(id) ON DELETE SET NULL, channel_session_id UUID REFERENCES channel_sessions(id) ON DELETE SET NULL, message_id UUID REFERENCES omnichannel_messages(id) ON DELETE SET NULL, conversation_id UUID REFERENCES conversations(id) ON DELETE SET NULL, event_type VARCHAR(80) NOT NULL, channel_type VARCHAR(60), title VARCHAR(220) NOT NULL, summary TEXT, event_payload JSONB NOT NULL DEFAULT '{}'::jsonb, occurred_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS channel_analytics (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, channel_config_id UUID REFERENCES channel_configurations(id) ON DELETE SET NULL, channel_type VARCHAR(60) NOT NULL, metric_name VARCHAR(80) NOT NULL, metric_value NUMERIC(14,3) NOT NULL, unit VARCHAR(32) NOT NULL DEFAULT 'count', dimensions JSONB NOT NULL DEFAULT '{}'::jsonb, captured_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_channel_config_workspace_status ON channel_configurations(workspace_id, channel_type, status);
CREATE INDEX IF NOT EXISTS ix_customer_identity_workspace_ref ON customer_identities(workspace_id, canonical_customer_ref);
CREATE INDEX IF NOT EXISTS ix_channel_sessions_workspace_status ON channel_sessions(workspace_id, channel_type, status, last_message_at);
CREATE INDEX IF NOT EXISTS ix_omnichannel_messages_workspace_channel ON omnichannel_messages(workspace_id, channel_type, created_at);
CREATE INDEX IF NOT EXISTS ix_delivery_events_message_status ON delivery_events(message_id, status, created_at);
CREATE INDEX IF NOT EXISTS ix_customer_timeline_workspace_customer ON customer_timeline_events(workspace_id, customer_identity_id, occurred_at);
CREATE INDEX IF NOT EXISTS ix_channel_analytics_workspace_metric ON channel_analytics(workspace_id, channel_type, metric_name, captured_at);
