CREATE TABLE IF NOT EXISTS connector_versions (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), connector_definition_id UUID NOT NULL REFERENCES connector_definitions(id) ON DELETE CASCADE, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, version VARCHAR(40) NOT NULL, status VARCHAR(40) NOT NULL DEFAULT 'draft', changelog TEXT, migration_guide TEXT, sdk_contract JSONB NOT NULL DEFAULT '{}'::jsonb, release_metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS connector_installations (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, connected_account_id UUID REFERENCES connected_accounts(id) ON DELETE SET NULL, external_integration_id UUID NOT NULL REFERENCES external_integrations(id) ON DELETE RESTRICT, connector_definition_id UUID REFERENCES connector_definitions(id) ON DELETE SET NULL, version_id UUID REFERENCES connector_versions(id) ON DELETE SET NULL, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, lifecycle_state VARCHAR(40) NOT NULL DEFAULT 'installed', install_stage VARCHAR(60) NOT NULL DEFAULT 'permission_review', permission_state JSONB NOT NULL DEFAULT '{}'::jsonb, configuration_state JSONB NOT NULL DEFAULT '{}'::jsonb, health_summary JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS connector_sync_jobs (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, connected_account_id UUID NOT NULL REFERENCES connected_accounts(id) ON DELETE CASCADE, job_type VARCHAR(60) NOT NULL DEFAULT 'manual', status VARCHAR(40) NOT NULL DEFAULT 'queued', cursor TEXT, conflict_count INTEGER NOT NULL DEFAULT 0, records_processed INTEGER NOT NULL DEFAULT 0, retry_count INTEGER NOT NULL DEFAULT 0, started_at TIMESTAMPTZ, finished_at TIMESTAMPTZ, error_message TEXT, metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS connector_marketplace_metadata (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), external_integration_id UUID NOT NULL REFERENCES external_integrations(id) ON DELETE CASCADE, developer_name VARCHAR(160), listing_status VARCHAR(40) NOT NULL DEFAULT 'published', rating_average VARCHAR(20), rating_count INTEGER NOT NULL DEFAULT 0, download_count INTEGER NOT NULL DEFAULT 0, install_count INTEGER NOT NULL DEFAULT 0, documentation JSONB NOT NULL DEFAULT '{}'::jsonb, screenshots JSONB NOT NULL DEFAULT '[]'::jsonb, dependency_map JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS connector_playground_runs (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, connected_account_id UUID REFERENCES connected_accounts(id) ON DELETE SET NULL, connector_definition_id UUID REFERENCES connector_definitions(id) ON DELETE SET NULL, run_type VARCHAR(60) NOT NULL DEFAULT 'action', status VARCHAR(40) NOT NULL DEFAULT 'completed', request_payload JSONB NOT NULL DEFAULT '{}'::jsonb, response_payload JSONB NOT NULL DEFAULT '{}'::jsonb, latency_ms INTEGER, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS connector_analytics_records (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, external_integration_id UUID REFERENCES external_integrations(id) ON DELETE SET NULL, connected_account_id UUID REFERENCES connected_accounts(id) ON DELETE SET NULL, metric_name VARCHAR(80) NOT NULL, metric_value VARCHAR(80) NOT NULL, dimensions JSONB NOT NULL DEFAULT '{}'::jsonb, captured_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_connector_versions_definition_status ON connector_versions(connector_definition_id, status, version);
CREATE INDEX IF NOT EXISTS ix_connector_installations_workspace_state ON connector_installations(workspace_id, lifecycle_state, deleted_at);
CREATE INDEX IF NOT EXISTS ix_connector_sync_jobs_connection_status ON connector_sync_jobs(connected_account_id, status, created_at);
CREATE INDEX IF NOT EXISTS ix_connector_marketplace_listing ON connector_marketplace_metadata(listing_status, install_count);
CREATE INDEX IF NOT EXISTS ix_connector_playground_workspace ON connector_playground_runs(workspace_id, run_type, created_at);
CREATE INDEX IF NOT EXISTS ix_connector_analytics_workspace_metric ON connector_analytics_records(workspace_id, metric_name, captured_at);