CREATE TABLE IF NOT EXISTS api_versions (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, version VARCHAR(40) NOT NULL UNIQUE, release_channel VARCHAR(40) NOT NULL DEFAULT 'stable', status VARCHAR(40) NOT NULL DEFAULT 'active', changelog TEXT, migration_guide_url TEXT, deprecation_notice TEXT, sunset_at TIMESTAMPTZ, openapi_ref TEXT, metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS oauth_access_tokens (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, oauth_application_id UUID NOT NULL REFERENCES oauth_applications(id) ON DELETE CASCADE, user_id UUID REFERENCES users(id) ON DELETE SET NULL, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, token_hash VARCHAR(128) NOT NULL, refresh_token_hash VARCHAR(128), scopes JSONB NOT NULL DEFAULT '[]'::jsonb, status VARCHAR(40) NOT NULL DEFAULT 'active', expires_at TIMESTAMPTZ, revoked_at TIMESTAMPTZ, metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS rate_limit_policies (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, name VARCHAR(180) NOT NULL, environment VARCHAR(40) NOT NULL DEFAULT 'development', subject_type VARCHAR(60) NOT NULL DEFAULT 'organization', subject_ref VARCHAR(180), endpoint_pattern TEXT, requests_per_minute INTEGER NOT NULL DEFAULT 600, burst_limit INTEGER NOT NULL DEFAULT 120, quota_limit INTEGER, quota_window VARCHAR(40) NOT NULL DEFAULT 'month', status VARCHAR(40) NOT NULL DEFAULT 'active', metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS sandbox_resources (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, resource_type VARCHAR(80) NOT NULL, name VARCHAR(180) NOT NULL, status VARCHAR(40) NOT NULL DEFAULT 'active', fixture_payload JSONB NOT NULL DEFAULT '{}'::jsonb, reset_policy JSONB NOT NULL DEFAULT '{}'::jsonb, metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS api_explorer_runs (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, api_key_id UUID REFERENCES api_keys(id) ON DELETE SET NULL, user_id UUID REFERENCES users(id) ON DELETE SET NULL, method VARCHAR(12) NOT NULL, path TEXT NOT NULL, request_headers JSONB NOT NULL DEFAULT '{}'::jsonb, request_body JSONB NOT NULL DEFAULT '{}'::jsonb, response_status INTEGER NOT NULL DEFAULT 200, response_headers JSONB NOT NULL DEFAULT '{}'::jsonb, response_body JSONB NOT NULL DEFAULT '{}'::jsonb, latency_ms INTEGER, timeline JSONB NOT NULL DEFAULT '[]'::jsonb, code_samples JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS cli_releases (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, version VARCHAR(40) NOT NULL UNIQUE, status VARCHAR(40) NOT NULL DEFAULT 'planned', install_command TEXT, supported_commands JSONB NOT NULL DEFAULT '[]'::jsonb, changelog TEXT, metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS sdk_releases (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, language VARCHAR(40) NOT NULL, package_name VARCHAR(160) NOT NULL, version VARCHAR(40) NOT NULL, status VARCHAR(40) NOT NULL DEFAULT 'planned', openapi_version VARCHAR(40), install_command TEXT, docs_url TEXT, metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS ix_api_versions_status ON api_versions(release_channel, status, sunset_at);
CREATE INDEX IF NOT EXISTS ix_oauth_tokens_app_status ON oauth_access_tokens(oauth_application_id, status, expires_at);
CREATE INDEX IF NOT EXISTS ix_rate_limit_policies_workspace_subject ON rate_limit_policies(workspace_id, subject_type, status);
CREATE INDEX IF NOT EXISTS ix_sandbox_resources_workspace_type ON sandbox_resources(workspace_id, resource_type, status);
CREATE INDEX IF NOT EXISTS ix_api_explorer_runs_workspace_created ON api_explorer_runs(workspace_id, created_at);
CREATE INDEX IF NOT EXISTS ix_cli_releases_status ON cli_releases(status, version);
CREATE INDEX IF NOT EXISTS ix_sdk_releases_language_status ON sdk_releases(language, status, version);