CREATE TABLE IF NOT EXISTS subscription_plans (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, slug VARCHAR(80) NOT NULL UNIQUE, name VARCHAR(160) NOT NULL, status VARCHAR(40) NOT NULL DEFAULT 'active', billing_interval VARCHAR(40) NOT NULL DEFAULT 'monthly', base_price_cents INTEGER NOT NULL DEFAULT 0, currency VARCHAR(12) NOT NULL DEFAULT 'usd', included_features JSONB NOT NULL DEFAULT '[]'::jsonb, usage_limits JSONB NOT NULL DEFAULT '{}'::jsonb, credit_allocation JSONB NOT NULL DEFAULT '{}'::jsonb, support_level VARCHAR(80) NOT NULL DEFAULT 'standard', metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS subscriptions (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, billing_account_id UUID NOT NULL REFERENCES billing_accounts(id) ON DELETE CASCADE, plan_id UUID REFERENCES subscription_plans(id) ON DELETE SET NULL, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, status VARCHAR(40) NOT NULL DEFAULT 'active', billing_interval VARCHAR(40) NOT NULL DEFAULT 'monthly', current_period_start TIMESTAMPTZ, current_period_end TIMESTAMPTZ, trial_end TIMESTAMPTZ, cancel_at TIMESTAMPTZ, provider_subscription_id VARCHAR(180), contract_ref VARCHAR(180), metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS billing_usage_records (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, subscription_id UUID REFERENCES subscriptions(id) ON DELETE SET NULL, meter_name VARCHAR(80) NOT NULL, quantity NUMERIC(18,6) NOT NULL, unit VARCHAR(40) NOT NULL DEFAULT 'count', source VARCHAR(80) NOT NULL DEFAULT 'platform', resource_type VARCHAR(80), resource_id VARCHAR(180), cost_cents INTEGER NOT NULL DEFAULT 0, occurred_at TIMESTAMPTZ, metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);CREATE TABLE IF NOT EXISTS credit_transactions (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, billing_account_id UUID NOT NULL REFERENCES billing_accounts(id) ON DELETE CASCADE, transaction_type VARCHAR(60) NOT NULL, credit_amount INTEGER NOT NULL, balance_after INTEGER NOT NULL DEFAULT 0, source VARCHAR(80) NOT NULL DEFAULT 'system', service_scope VARCHAR(80), expires_at TIMESTAMPTZ, metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS billing_quotas (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, meter_name VARCHAR(80) NOT NULL, limit_type VARCHAR(40) NOT NULL DEFAULT 'soft', limit_value NUMERIC(18,6) NOT NULL, warning_threshold NUMERIC(8,4), current_usage NUMERIC(18,6) NOT NULL DEFAULT 0, period_start TIMESTAMPTZ, period_end TIMESTAMPTZ, grace_policy JSONB NOT NULL DEFAULT '{}'::jsonb, status VARCHAR(40) NOT NULL DEFAULT 'active', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS invoices (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, billing_account_id UUID NOT NULL REFERENCES billing_accounts(id) ON DELETE CASCADE, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, invoice_number VARCHAR(80) NOT NULL UNIQUE, status VARCHAR(40) NOT NULL DEFAULT 'draft', currency VARCHAR(12) NOT NULL DEFAULT 'usd', subtotal_cents INTEGER NOT NULL DEFAULT 0, discount_cents INTEGER NOT NULL DEFAULT 0, credits_applied_cents INTEGER NOT NULL DEFAULT 0, tax_cents INTEGER NOT NULL DEFAULT 0, total_cents INTEGER NOT NULL DEFAULT 0, provider_invoice_id VARCHAR(180), pdf_file_id UUID REFERENCES files(id) ON DELETE SET NULL, issued_at TIMESTAMPTZ, due_at TIMESTAMPTZ, paid_at TIMESTAMPTZ, metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS invoice_line_items (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, invoice_id UUID NOT NULL REFERENCES invoices(id) ON DELETE CASCADE, description TEXT NOT NULL, meter_name VARCHAR(80), quantity NUMERIC(18,6), unit_amount_cents INTEGER NOT NULL DEFAULT 0, amount_cents INTEGER NOT NULL DEFAULT 0, metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS discounts (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, code VARCHAR(80) NOT NULL, discount_type VARCHAR(40) NOT NULL DEFAULT 'percentage', value NUMERIC(12,4) NOT NULL, status VARCHAR(40) NOT NULL DEFAULT 'active', starts_at TIMESTAMPTZ, ends_at TIMESTAMPTZ, rules JSONB NOT NULL DEFAULT '{}'::jsonb, metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS billing_profiles (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, billing_account_id UUID NOT NULL REFERENCES billing_accounts(id) ON DELETE CASCADE, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, company_name VARCHAR(220), billing_email VARCHAR(320), billing_contacts JSONB NOT NULL DEFAULT '[]'::jsonb, address JSONB NOT NULL DEFAULT '{}'::jsonb, tax_info JSONB NOT NULL DEFAULT '{}'::jsonb, invoice_preferences JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS enterprise_contracts (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, billing_account_id UUID NOT NULL REFERENCES billing_accounts(id) ON DELETE CASCADE, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, contract_number VARCHAR(100) NOT NULL UNIQUE, status VARCHAR(40) NOT NULL DEFAULT 'draft', pricing_model VARCHAR(60) NOT NULL DEFAULT 'hybrid', start_date TIMESTAMPTZ, end_date TIMESTAMPTZ, committed_amount_cents INTEGER NOT NULL DEFAULT 0, terms JSONB NOT NULL DEFAULT '{}'::jsonb, metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS payment_provider_configs (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, provider VARCHAR(80) NOT NULL, status VARCHAR(40) NOT NULL DEFAULT 'disabled', priority INTEGER NOT NULL DEFAULT 100, secret_ref TEXT, capabilities JSONB NOT NULL DEFAULT '[]'::jsonb, config JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS payment_methods (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, billing_account_id UUID NOT NULL REFERENCES billing_accounts(id) ON DELETE CASCADE, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, provider VARCHAR(80) NOT NULL, provider_payment_method_id VARCHAR(180), method_type VARCHAR(60) NOT NULL DEFAULT 'card', display_name VARCHAR(180), status VARCHAR(40) NOT NULL DEFAULT 'active', billing_details JSONB NOT NULL DEFAULT '{}'::jsonb, metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS budget_controls (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, name VARCHAR(180) NOT NULL, scope_type VARCHAR(60) NOT NULL DEFAULT 'workspace', scope_ref VARCHAR(180), monthly_budget_cents INTEGER NOT NULL DEFAULT 0, hard_cap_cents INTEGER, alert_thresholds JSONB NOT NULL DEFAULT '[]'::jsonb, forecast_state JSONB NOT NULL DEFAULT '{}'::jsonb, status VARCHAR(40) NOT NULL DEFAULT 'active', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS billing_analytics_records (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, metric_name VARCHAR(80) NOT NULL, metric_value NUMERIC(18,6) NOT NULL, currency VARCHAR(12), plan_slug VARCHAR(80), dimensions JSONB NOT NULL DEFAULT '{}'::jsonb, captured_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_subscriptions_org_status ON subscriptions(organization_id, status, current_period_end);
CREATE INDEX IF NOT EXISTS ix_billing_usage_records_workspace_meter ON billing_usage_records(workspace_id, meter_name, occurred_at);
CREATE INDEX IF NOT EXISTS ix_credit_transactions_account ON credit_transactions(billing_account_id, transaction_type, created_at);
CREATE INDEX IF NOT EXISTS ix_billing_quotas_workspace_meter ON billing_quotas(workspace_id, meter_name, status);
CREATE INDEX IF NOT EXISTS ix_invoices_account_status ON invoices(billing_account_id, status, issued_at);
CREATE INDEX IF NOT EXISTS ix_invoice_line_items_invoice ON invoice_line_items(invoice_id, meter_name);
CREATE INDEX IF NOT EXISTS ix_discounts_org_status ON discounts(organization_id, status, code);
CREATE INDEX IF NOT EXISTS ix_payment_methods_account_status ON payment_methods(billing_account_id, status);
CREATE INDEX IF NOT EXISTS ix_budget_controls_workspace_status ON budget_controls(workspace_id, status);
CREATE INDEX IF NOT EXISTS ix_billing_analytics_org_metric ON billing_analytics_records(organization_id, metric_name, captured_at);