"use client";

import type { ReactNode } from "react";
import { CheckCircle2, FileSearch, RefreshCw, Search, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { Badge, Button, EmptyState, ErrorState, Progress, SearchInput, Skeleton } from "@voicesense/ui";
import { accessModels, complianceFrameworks, governancePolicies, riskControls, securityEvents, securityReadiness, securityStats } from "../../../lib/security-data";

export default function SecurityPage() {
  return (
    <div className="security-page">
      <header className="security-hero"><div><p className="ws-kicker">Security and governance</p><h1>Administer identity, access, compliance, secrets, audit trails, risk, and AI governance from one enterprise control plane.</h1><p>VoiceSense security is policy-first: RBAC, ABAC, SSO, MFA, data governance, and auditability are modeled as platform capabilities that every future product area can inherit.</p></div><div className="security-actions"><Button><ShieldCheck size={16} />Review posture</Button><Button variant="outline"><SlidersHorizontal size={16} />Policies</Button><Button variant="outline"><FileSearch size={16} />Audit</Button></div></header>
      <section className="security-stat-grid">{securityStats.map((stat) => <article className={`security-card security-stat ${stat.tone}`} key={stat.label}><stat.icon size={18} /><p>{stat.label}</p><strong>{stat.value}</strong><span>{stat.detail}</span></article>)}</section>
      <section className="security-toolbar"><div className="security-category-row"><button className="is-active" type="button">Overview</button><button type="button">Access</button><button type="button">Compliance</button><button type="button">Audit</button><button type="button">Risk</button></div><div className="security-search"><SearchInput placeholder="Search policies, users, secrets" /><Button variant="outline" size="sm"><Search size={15} />Search</Button></div></section>
      <section className="security-main-grid"><div className="security-left-stack"><SecurityPanel title="Governance policies" action={<Button variant="outline" size="sm"><RefreshCw size={15} />Refresh</Button>}><div className="security-table"><div className="security-row security-head"><span>Policy</span><span>Scope</span><span>Mode</span><span>Status</span></div>{governancePolicies.map((policy) => <div className="security-row" key={policy.name}><span><CheckCircle2 size={15} />{policy.name}</span><span>{policy.scope}</span><span>{policy.mode}</span><span><Badge variant={policy.status === "Active" ? "success" : "warning"}>{policy.status}</Badge></span></div>)}</div></SecurityPanel><SecurityPanel title="Identity and access model"><div className="security-access-grid">{accessModels.map((item) => <article key={item.label}><item.icon size={18} /><strong>{item.label}</strong><p>{item.value}</p></article>)}</div></SecurityPanel><SecurityPanel title="Audit and risk timeline"><div className="security-timeline">{securityEvents.map((event) => <div className="security-event" key={`${event.time}-${event.title}`}><span>{event.time}</span><event.icon size={16} /><div><strong>{event.title}</strong><p>{event.detail}</p></div></div>)}</div></SecurityPanel></div><aside className="security-side-stack"><SecurityPanel title="Compliance center"><div className="security-compliance-grid">{complianceFrameworks.map((item) => <div key={item.label}><span><strong>{item.label}</strong><small>{item.value}</small></span><Progress value={item.progress} /></div>)}</div></SecurityPanel><SecurityPanel title="Risk controls"><div className="security-chip-row">{riskControls.map((control) => <span key={control}>{control}</span>)}</div></SecurityPanel><SecurityPanel title="Platform readiness"><div className="security-readiness-grid">{securityReadiness.map((item) => <div key={item.label}><item.icon size={16} /><span>{item.label}</span><strong>{item.value}</strong></div>)}</div></SecurityPanel></aside></section>
      <section className="security-bottom-grid"><EmptyState title="Live IdP provisioning deferred" description="SSO connection records, MFA factors, trusted devices, sessions, and audit APIs are ready. SCIM provisioning and IdP-specific flows remain future integration work." action={<Button variant="outline" size="sm">Review SSO model</Button>} /><ErrorState title="Compliance certifications are not claimed" description="Task 026 creates evidence, control, and readiness foundations only. Formal SOC 2, ISO 27001, HIPAA, and GDPR programs still require legal and operational review." onRetry={() => undefined} /><div className="security-card"><Skeleton className="security-skeleton" /><Skeleton className="security-skeleton-line" /><Skeleton className="security-skeleton-line" /></div></section>
    </div>
  );
}

function SecurityPanel({ title, action, children }: { title: string; action?: ReactNode; children: ReactNode }) { return <article className="security-card"><div className="security-panel-head"><h2>{title}</h2>{action}</div>{children}</article>; }