"use client";

import type { ReactNode } from "react";
import { CreditCard, Download, Plus, RefreshCw, Search, Settings } from "lucide-react";
import { Badge, Button, EmptyState, ErrorState, Progress, SearchInput, Skeleton } from "@voicesense/ui";
import { billingReadiness, billingStats, costBreakdown, creditLedger, invoices, planFeatures, providerReadiness, usageMeters } from "../../../lib/billing-data";

export default function BillingPage() {
  return (
    <div className="billing-page">
      <header className="billing-hero"><div><p className="ws-kicker">Billing and monetization</p><h1>Track subscriptions, usage, credits, invoices, quotas, budgets, and enterprise contracts with full financial transparency.</h1><p>VoiceSense billing is provider-agnostic by design: payment providers, tax systems, PDF generation, and marketplace revenue can be swapped behind stable billing contracts.</p></div><div className="billing-actions"><Button><CreditCard size={16} />Manage plan</Button><Button variant="outline"><Plus size={16} />Add credits</Button><Button variant="outline"><Settings size={16} />Settings</Button></div></header>
      <section className="billing-stat-grid">{billingStats.map((stat) => <article className={`billing-card billing-stat ${stat.tone}`} key={stat.label}><stat.icon size={18} /><p>{stat.label}</p><strong>{stat.value}</strong><span>{stat.detail}</span></article>)}</section>
      <section className="billing-toolbar"><div className="billing-category-row"><button className="is-active" type="button">Overview</button><button type="button">Usage</button><button type="button">Credits</button><button type="button">Invoices</button><button type="button">Contracts</button></div><div className="billing-search"><SearchInput placeholder="Search invoices, meters, contracts" /><Button variant="outline" size="sm"><Search size={15} />Search</Button></div></section>
      <section className="billing-main-grid"><div className="billing-left-stack"><BillingPanel title="Live usage dashboard" action={<Button variant="outline" size="sm"><RefreshCw size={15} />Refresh</Button>}><div className="billing-meter-grid">{usageMeters.map((meter) => <article key={meter.name}><meter.icon size={18} /><strong>{meter.name}</strong><p>{meter.value} of {meter.limit}</p><Progress value={meter.progress} /></article>)}</div></BillingPanel><BillingPanel title="Invoice center" action={<Button variant="outline" size="sm"><Download size={15} />Export</Button>}><div className="billing-table"><div className="billing-row billing-head"><span>Invoice</span><span>Status</span><span>Amount</span><span>Issued</span><span>Due</span></div>{invoices.map((invoice) => <div className="billing-row" key={invoice.number}><span>{invoice.number}</span><span><Badge variant={invoice.status === "Paid" ? "success" : invoice.status === "Open" ? "warning" : "info"}>{invoice.status}</Badge></span><span>{invoice.amount}</span><span>{invoice.issued}</span><span>{invoice.due}</span></div>)}</div></BillingPanel><BillingPanel title="Credit ledger"><div className="billing-table"><div className="billing-row billing-head"><span>Type</span><span>Amount</span><span>Balance</span><span>Scope</span><span>Status</span></div>{creditLedger.map((item) => <div className="billing-row" key={`${item.type}-${item.balance}`}><span>{item.type}</span><span>{item.amount}</span><span>{item.balance}</span><span>{item.scope}</span><span><Badge>posted</Badge></span></div>)}</div></BillingPanel></div><aside className="billing-side-stack"><BillingPanel title="Current plan"><div className="billing-plan"><strong>Business</strong><p>$499/month plus usage overages</p><div className="billing-chip-row">{planFeatures.map((feature) => <span key={feature}>{feature}</span>)}</div></div></BillingPanel><BillingPanel title="Cost breakdown"><div className="billing-readiness-grid">{costBreakdown.map((item) => <div key={item.label}><item.icon size={16} /><span>{item.label}</span><strong>{item.value}</strong></div>)}</div></BillingPanel><BillingPanel title="Payment providers"><div className="billing-chip-row">{providerReadiness.map((provider) => <span key={provider}>{provider}</span>)}</div></BillingPanel></aside></section>
      <section className="billing-bottom-grid"><BillingPanel title="Platform readiness"><div className="billing-readiness-grid">{billingReadiness.map((item) => <div key={item.label}><item.icon size={16} /><span>{item.label}</span><strong>{item.value}</strong></div>)}</div></BillingPanel><EmptyState title="Live payment processing deferred" description="Provider abstraction, invoices, credits, quotas, budgets, and analytics are modeled. Real payment capture and tax compliance remain out of scope for Task 025." action={<Button variant="outline" size="sm">Review providers</Button>} /><div className="billing-card"><Skeleton className="billing-skeleton" /><Skeleton className="billing-skeleton-line" /><Skeleton className="billing-skeleton-line" /></div></section>
      <section className="billing-state-grid"><ErrorState title="Accounting integrations not included" description="Financial accounting exports and marketplace revenue sharing are intentionally deferred." onRetry={() => undefined} /><EmptyState title="Enterprise contract manager ready" description="Seat, usage, flat-rate, and hybrid contract models can now be represented without custom code." /></section>
    </div>
  );
}

function BillingPanel({ title, action, children }: { title: string; action?: ReactNode; children: ReactNode }) { return <article className="billing-card"><div className="billing-panel-head"><h2>{title}</h2>{action}</div>{children}</article>; }