"use client";
import * as React from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card, CardContent, CardHeader, CardTitle } from "../data-display/card";

const palette = ["#0F766E", "#2F6EEA", "#B86B16", "#6D55D9", "#0E7490"];
export function ChartFrame({ title, children }: { title: string; children: React.ReactNode }) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent><div className="vs-chart-frame">{children}</div></CardContent></Card>; }
export function LineChartCard({ title, data, xKey, yKey }: { title: string; data: Record<string, number | string>[]; xKey: string; yKey: string }) { return <ChartFrame title={title}><ResponsiveContainer width="100%" height="100%"><LineChart data={data}><CartesianGrid stroke="#E4E1DA" /><XAxis dataKey={xKey} /><YAxis /><Tooltip /><Line dataKey={yKey} stroke="#0F766E" strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer></ChartFrame>; }
export function AreaChartCard({ title, data, xKey, yKey }: { title: string; data: Record<string, number | string>[]; xKey: string; yKey: string }) { return <ChartFrame title={title}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><CartesianGrid stroke="#E4E1DA" /><XAxis dataKey={xKey} /><YAxis /><Tooltip /><Area dataKey={yKey} fill="#DDF4EF" stroke="#0F766E" /></AreaChart></ResponsiveContainer></ChartFrame>; }
export function BarChartCard({ title, data, xKey, yKey }: { title: string; data: Record<string, number | string>[]; xKey: string; yKey: string }) { return <ChartFrame title={title}><ResponsiveContainer width="100%" height="100%"><BarChart data={data}><CartesianGrid stroke="#E4E1DA" /><XAxis dataKey={xKey} /><YAxis /><Tooltip /><Bar dataKey={yKey} fill="#2F6EEA" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></ChartFrame>; }
export function PieChartCard({ title, data, nameKey, dataKey }: { title: string; data: Record<string, number | string>[]; nameKey: string; dataKey: string }) { return <ChartFrame title={title}><ResponsiveContainer width="100%" height="100%"><PieChart><Tooltip /><Pie data={data} nameKey={nameKey} dataKey={dataKey} innerRadius={42} outerRadius={76}>{data.map((_, index) => <Cell key={index} fill={palette[index % palette.length]} />)}</Pie></PieChart></ResponsiveContainer></ChartFrame>; }
export function KpiCard({ label, value, delta }: { label: string; value: string; delta?: string }) { return <Card variant="stat"><CardContent><p className="vs-kpi-label">{label}</p><strong className="vs-kpi-value">{value}</strong>{delta ? <span className="vs-kpi-delta">{delta}</span> : null}</CardContent></Card>; }