"use client";

import type { ReactNode } from "react";
import { Copy, GitCompare, Play, Plus, Rocket, Search, Settings, Wand2 } from "lucide-react";
import { Badge, Button, EmptyState, ErrorState, Progress, SearchInput, Skeleton } from "@voicesense/ui";
import { aiTimeline, collaboration, evaluationMetrics, experiments, promptVersions, studioLifecycle, studioReadiness, studioStats, templates } from "../../../lib/studio-data";

export default function StudioPage() {
  return (
    <div className="studio-page">
      <header className="studio-hero"><div><p className="ws-kicker">AI Studio</p><h1>Build, test, evaluate, compare, deploy, replay, and continuously improve AI Employees from one engineering-grade workspace.</h1><p>AI Studio combines prompt versioning, simulation, evaluation, regression tests, benchmarks, experiments, deployment gates, collaboration, and interaction timelines without locking VoiceSense to any single model provider.</p></div><div className="studio-actions"><Button><Plus size={16} />New prompt</Button><Button variant="outline"><Play size={16} />Run simulation</Button><Button variant="outline"><Rocket size={16} />Deploy</Button></div></header>
      <section className="studio-stat-grid">{studioStats.map((stat) => <article className={`studio-card studio-stat ${stat.tone}`} key={stat.label}><stat.icon size={18} /><p>{stat.label}</p><strong>{stat.value}</strong><span>{stat.detail}</span></article>)}</section>
      <section className="studio-toolbar"><div className="studio-category-row"><button className="is-active" type="button">Overview</button><button type="button">Builder</button><button type="button">Playground</button><button type="button">Evaluations</button><button type="button">Deployments</button></div><div className="studio-search"><SearchInput placeholder="Search prompts, tests, experiments" /><Button variant="outline" size="sm"><Search size={15} />Search</Button></div></section>
      <section className="studio-main-grid"><div className="studio-left-stack"><StudioPanel title="Prompt builder" action={<Button size="sm"><Wand2 size={15} />Validate</Button>}><div className="studio-editor"><div><span>System instructions</span><pre>{`You are Maya, a calm customer support AI employee.\nUse company knowledge before answering.\nEscalate billing disputes above $250.`}</pre></div><div><span>Variables</span><code>{`{{customer_name}} {{plan}} {{last_order}}`}</code></div><div><span>Guardrails</span><code>Refunds require policy match + human approval for exceptions.</code></div></div></StudioPanel><StudioPanel title="Prompt version comparison" action={<Button variant="outline" size="sm"><GitCompare size={15} />Compare</Button>}><div className="studio-table"><div className="studio-row studio-head"><span>Version</span><span>Status</span><span>Score</span><span>Cost</span><span>Latency</span></div>{promptVersions.map((item) => <div className="studio-row" key={item.version}><span>{item.version}</span><span><Badge variant={item.status === "Production" ? "success" : item.status === "Draft" ? "warning" : "info"}>{item.status}</Badge></span><span>{item.score}</span><span>{item.cost}</span><span>{item.latency}</span></div>)}</div></StudioPanel><StudioPanel title="AI interaction timeline"><div className="studio-timeline">{aiTimeline.map((item) => <div className="studio-event" key={item.step}><item.icon size={16} /><div><strong>{item.step}</strong><p>{item.detail}</p></div></div>)}</div></StudioPanel></div><aside className="studio-side-stack"><StudioPanel title="AI engineering lifecycle"><div className="studio-lifecycle">{studioLifecycle.map((item) => <article key={item.label}><item.icon size={16} /><strong>{item.label}</strong><p>{item.value}</p></article>)}</div></StudioPanel><StudioPanel title="Evaluation dashboard"><div className="studio-eval-grid">{evaluationMetrics.map((item) => <div key={item.label}><span><strong>{item.label}</strong><small>{item.value}</small></span><Progress value={item.progress} /></div>)}</div></StudioPanel><StudioPanel title="Template library"><div className="studio-chip-row">{templates.map((template) => <span key={template}>{template}</span>)}</div></StudioPanel></aside></section>
      <section className="studio-bottom-grid"><StudioPanel title="Experiment workspace"><div className="studio-table compact">{experiments.map((item) => <div className="studio-exp" key={item.name}><strong>{item.name}</strong><span>{item.target}</span><Badge>{item.lift}</Badge><small>{item.status}</small></div>)}</div></StudioPanel><StudioPanel title="Collaboration timeline"><div className="studio-timeline">{collaboration.map((item) => <div className="studio-activity" key={`${item.time}-${item.title}`}><span>{item.time}</span><item.icon size={16} /><div><strong>{item.title}</strong><p>{item.detail}</p></div></div>)}</div></StudioPanel><StudioPanel title="Readiness map"><div className="studio-chip-row">{studioReadiness.map((item) => <span key={item}>{item}</span>)}</div></StudioPanel></section>
      <section className="studio-state-grid"><EmptyState title="Runtime prompt execution deferred" description="AI Studio stores prompt, evaluation, simulation, benchmark, deployment, replay, and analytics records. Live model execution will plug into provider adapters later." action={<Button variant="outline" size="sm"><Settings size={15} />Review architecture</Button>} /><ErrorState title="Autonomous optimization is out of scope" description="Task 027 intentionally excludes automatic prompt generation, RL systems, and model training pipelines." onRetry={() => undefined} /><div className="studio-card"><Skeleton className="studio-skeleton" /><Skeleton className="studio-skeleton-line" /><Skeleton className="studio-skeleton-line" /></div></section>
    </div>
  );
}

function StudioPanel({ title, action, children }: { title: string; action?: ReactNode; children: ReactNode }) { return <article className="studio-card"><div className="studio-panel-head"><h2>{title}</h2>{action}</div>{children}</article>; }